### ISSUE TITLE
Minor changes to csvs

### ISSUE THREAD

**Issue by dlebauer** [az-digitalag/ardn-terra-ref#9]
**Task to do**

I think we should use names rather than integers for the keys, as you have done with germplasmName; 

It is possible / likely that people will prefer these CSV files over the JSON files ... as you have already done the hard work making these tables ready for analysis!

- [ ] add studyName and observationName fields; add these to tables that currently have studyDbId and observationDbId.
-  [ ] events_table doesn't need studyDbId (or study name) since it can be joined via the observations table; its redundancy adds a circular reference and may cause confusion (e.g. people wondering why it is there, or thinking they should join events and studies together on studyDbId). 
- [ ] please add  treatments$factor as treatment or treatmentName to observations because it is required to interpret the data
- [ ] update this table relationships figure on [google docs](https://docs.google.com/drawings/d/1LJ7vXk-YTTkZI9-qI25sTCvmnUYH3qENaT74Nh7UQM8/edit) and replace one currently in repository 

**Reason**

Consistency, clarity, providing useful information

**Result**

Hopefully this only updates the tables and doesn't change the downstream steps (e.g. ask vmapper to ignore these extra fields)
